language: node_js
node_js: 6.3.0

script:
  - npm run build
  - npm test

deploy:
    skip_cleanup: true
    api_key: $NPM_KEY
    email: $NPM_EMAIL
    on: { tags: true }

notifications:
  email: false
  slack: $SLACK_KEY

env:
  global:
    - NODE_ENV=development
    - DASH_ASSETS_BASE="https://components.dashaudio.co/versions/v$(node version.js)"
